### PR TITLE
Refactor plugin

### PR DESCRIPTION
**Pull request by cossssmin**
This PR:

- updates the boilerplate and code (a754aa1)
- adds wrapping tag only when specified through attribute (ff383e4)
- adds attributes support (fe6c528)
- adds a test for markdown-it options (1ef6bae)

I've also updated the README and used more explicit test names.

Travis config has been updated to test against Node `stable`, `12`, and `10`.

### CODE REVIEW

**Comment by cossssmin** [comment]
@TheComputerM or @Scrum please enable this repo in Travis CI. And let me know what you think, I can't add reviewers...

**Comment by TheComputerM** [comment]
Nice work, enabled this repo in Travis CI

**Comment by cossssmin** [comment]
Awesome, thanks! Can you please also publish a release on NPM? 

Think I’m going to use your plugin in a framework, it might solve a few issues that I’m running into 👍

**Comment by TheComputerM** [comment]
Will do, just adding and improving some tests.

The tests do not run successfully, did they run properly in your system?

**Comment by cossssmin** [comment]
Yes they do (see [here](https://travis-ci.org/github/cossssmin/posthtml-markdownit)). Make sure the test HTML files are LF (not CRLF). I also suggest installing the EditorConfig plugin for your editor - the `.editorconfig` file will then work and new files you create should be LF (unless you have some settings overriding it in your editor).

If you want, just open the PR and I can help fix the files 👍

**Comment by cossssmin** [comment]
Thanks for releasing 1.2!

Btw, Travis hasn't run any builds, might want to trigger one manually and check the settings.

**Comment by TheComputerM** [comment]
Added [husky](https://www.npmjs.com/package/husky), instead of Travis, so if there is any faulty code, we would not push it before testing.

**Comment by cossssmin** [comment]
OK, but Travis is for continuous integration, you can't replace it with a precommit hook...

**Comment by TheComputerM** [comment]
I have not worked much with CI before, which do you recommend. I have Travis CI set up for pull requests and do not think it is necessary to set it up for pushes.

**Comment by cossssmin** [comment]
I would recommend leaving the defaults in Travis (so enable push too) - sometimes, like you just did, you'll push directly instead of opening a PR 🙂

So you can leave husky if you want, just enable on push in Travis. To trigger a build manually, go to the [project in Travis](https://travis-ci.org/github/posthtml/posthtml-markdownit) and use the menu on the right:

image

**Comment by TheComputerM** [comment]
Done 👍

**Comment by cossssmin** [comment]
Thank you for your work - been playing with the plugin and it works great! 👍

**Pull request merged**
